// Generated by CoffeeScript 1.9.3
(function() {
  var app, express, server;

  express = require('express');

  app = express();

  app.use(express["static"]('static'));

  app.get('/', function(req, res) {
    return res.send('Hello World!!!');
  });

  server = app.listen(3000, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('Example app listening at http://%s:%s', host, port);
  });

}).call(this);
