// Generated by CoffeeScript 1.9.2
(function() {
  var app, express, server;

  express = require('express');

  app = express();

  app.set('port', process.env.PORT || 5000);

  app.use(express["static"](__dirname + '/public'));

  app.get('/', function(req, res) {
    return res.send('Hello World!!!');
  });

  server = app.listen(app.get('port'), function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('Example app listening at http://%s:%s', host, port);
  });

}).call(this);
